# Generated by Django 5.2.4 on 2026-02-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_address_user_city_user_pincode_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
