# Generated by Django 5.2.4 on 2026-02-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_providerprofile_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
