# Generated by Django 5.2.4 on 2026-02-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_address_booking_city_booking_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='state',
        ),
    ]
